# stop.yaml - Ansible playbook for stopping a simple blog environment in Docker
#             containers with Postgres
#
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Stop the app"
      docker_container:
        name: simpleblog_app
        state: absent

    - name: "Start DB container"
      docker_container:
        name: simpleblog_db
        state: absent
        keep_volumes: yes
